# Generated by Django 6.1.1 on 2026-09-16 07:31

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(default=core.models.generate_code, max_length=6, unique=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('game_status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('finished', 'Finished')], default='setup', max_length=16)),
                ('house_name', models.CharField(blank=True, max_length=160)),
                ('house_address', models.TextField(blank=True)),
                ('house_notes', models.TextField(blank=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=120)),
                ('wifi_password', models.CharField(blank=True, max_length=120)),
                ('door_code', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_alive', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.trip')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'name'), name='unique_player_name')],
            },
        ),
    ]
