# Generated by Django 6.1.1 on 2026-09-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='game_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
