# Generated by Django 6.1.1 on 2026-09-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trip_game_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='door_code',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='house_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='house_notes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='wifi_password',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='wifi_ssid',
        ),
    ]
