# Generated by Django 6.1.1 on 2026-09-18 14:30

import secrets

import core.models
from django.db import migrations, models


def assign_pins(apps, schema_editor):
    Player = apps.get_model("core", "Player")
    for player in Player.objects.all():
        player.pin = f"{secrets.randbelow(10_000):04d}"
        player.save(update_fields=["pin"])


def clear_pins(apps, schema_editor):
    Player = apps.get_model("core", "Player")
    Player.objects.update(pin="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trip_options_remove_trip_door_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pin',
            field=models.CharField(default=core.models.generate_pin, editable=False, max_length=4),
        ),
        migrations.RunPython(assign_pins, clear_pins),
    ]
