# Generated by Django 6.1.1 on 2026-09-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('system', 'System'), ('announcement', 'Announcement')], default='system', max_length=16),
        ),
    ]
