# Generated by Django 6.1.1 on 2026-09-16 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_text', models.CharField(max_length=120)),
                ('location_text', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_given', to='core.player')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_received', to='core.player')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.trip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_text', models.CharField(max_length=120)),
                ('location_text', models.CharField(max_length=120)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills_as_killer', to='core.player')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='core.trip')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills_as_victim', to='core.player')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='KillAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied')], default='pending', max_length=16)),
                ('weapon_text', models.CharField(blank=True, max_length=120)),
                ('location_text', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_initiated', to='core.player')),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_as_killer', to='core.player')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_attempts', to='core.trip')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_as_victim', to='core.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='core.player')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.trip')),
            ],
            options={
                'ordering': ['text'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'text'), name='unique_location_per_trip')],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='core.player')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.trip')),
            ],
            options={
                'ordering': ['text'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'text'), name='unique_weapon_per_trip')],
            },
        ),
    ]
