# Generated by Django 6.1.1 on 2026-09-19 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_assignment_game_number_kill_game_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_text', models.CharField(max_length=120)),
                ('location_text', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadouts', to='game.assignment')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
